#pragma once
#include "Platform/platform.h"
#include "Platform/windows.h"
typedef void* LPDIRECT3D9;
typedef void* LPDIRECT3DDEVICE9;
typedef void* LPDIRECT3DTEXTURE9;
#define D3D_SDK_VERSION 32
typedef struct _D3DVERTEXELEMENT9 { WORD Stream; WORD Offset; BYTE Type; BYTE Method; BYTE Usage; BYTE UsageIndex; } D3DVERTEXELEMENT9;
#define D3DDECLTYPE_FLOAT1 0
#define D3DDECLTYPE_FLOAT2 1
#define D3DDECLTYPE_FLOAT3 2
#define D3DDECLTYPE_FLOAT4 3
#define D3DDECLMETHOD_DEFAULT 0
#define D3DDECLUSAGE_POSITION 0
#define D3DDECLUSAGE_NORMAL 3
#define D3DDECLUSAGE_TEXCOORD 5
#ifndef D3DDECL_END
#define D3DDECL_END() {0xFF,0,0,0,0,0}
#endif
#ifndef D3DDECLUSAGE_BLENDWEIGHT
#define D3DDECLUSAGE_BLENDWEIGHT 1
#define D3DDECLUSAGE_BLENDINDICES 2
#define D3DDECLUSAGE_POSITIONT 9
#define D3DDECLUSAGE_PSIZE 10
#define D3DDECLTYPE_UBYTE4 5
#define D3DDECLTYPE_SHORT2 6
#endif
#ifndef D3DDECLUSAGE_TANGENT
#define D3DDECLUSAGE_TANGENT 6
#define D3DDECLUSAGE_BINORMAL 7
#define D3DDECLUSAGE_TESSFACTOR 8
#define D3DDECLUSAGE_COLOR 10
#define D3DDECLUSAGE_FOG 11
#define D3DDECLUSAGE_DEPTH 12
#define D3DDECLUSAGE_SAMPLE 13
#define D3DDECLTYPE_D3DCOLOR 4
#endif
