execute_process(COMMAND python3 /tmp/audit_case2.py OUTPUT_VARIABLE out ERROR_VARIABLE err RESULT_VARIABLE res)
if(NOT res EQUAL 0)
  message(FATAL_ERROR "audit failed: ${err}")
endif()
string(FIND "${out}" "Total mismatches: 0" found)
if(found EQUAL -1)
  message(FATAL_ERROR "Case mismatches:\n${out}")
else()
  message(STATUS "check_case: 0 mismatches (graphify 7888 files)")
endif()
